### ISSUE TITLE
如何离线加载模型文件部署运行

### ISSUE THREAD

**Issue by mengweiquan** [modelscope/modelscope-classroom#4]
模型通过snapshot_download加载下载好了，如何离线加载模型文件部署运行呢?
尝试使用 AutoModelForSequenceClassification.from_pretrained(local_model_path) AutoTokenizer.from_pretrained(local_model_path)  加载Qwen1.5-4B-Chat ，出现如下错误
Some weights of Qwen2ForSequenceClassification were not initialized from the model checkpoint at /home/zhh123./.cache/modelscope/hub/qwen/Qwen1.5-4B-Chat and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

**Comment by wenmengzhou** [comment]
使用AutoModel.from_pretrained，Qwen1.5没有支持AutoModelForSequenceClassification
